### ISSUE TITLE
Cannot get past the first screen when creating a new map

### ISSUE THREAD

**Issue by 2michaelhammond** [newrelic/nr1-workload-geoops#142]
## Description

I cannot create a new map.  The application does not advance from the "Create a map" step to the "Define Locations" step.

## Steps to Reproduce

1) Select GeoOps (Public) from list of NR1 Apps
2) Select "New Map"
3) Fill in details on the "Create a Map" screen
4) Click on "Continue"

Nothing happens after that

## Expected Behaviour

I expect to progress to the second screen "Define Locations"

## Relevant Logs / Console output

I see this error in the Dev Console: "DOMException: Blocked a frame with origin "https://one.newrelic.com" from accessing a cross-origin frame."

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* NR1 CLI version used:
* Browser name and version:
* Operating System and version:

## Additional context

[TIP]:  # ( Add any other context about the problem here. )

**Comment by jpvajda** [comment]
@bobj82 was going to take a look at this issue and let us know if we need to assist.

**Comment by pmoore123456789** [comment]
I have this issue too. Multiple browsers, and same problem. Clicking each step at the top takes you to it but the settings do not commit and the continue button does not work. Also tried the JSON upload method but none of the workloads appear in the list so can't assign to a location. Browser console indicates multiple JS errors

**Comment by jpvajda** [comment]
@bobj82 have you made any progress on resolving this?

**Comment by bobj82** [comment]
Since the catalog(Public) version and my local version are unchanged, this is outside the scope of what we can fix within this code without some direction. _Mike and I need someone to solve this issue_. 

I have 
- **not** made any progress. 
- escalated the issue and provided the attached browser console log.   
- tested the behavior with a standalone version running nerdpack:serve --verbose that is unchanged and worked properly prior to the problem appearing.
- tested the behavior using the public app accessible from my New Relic email. 
- tested with both Chrome and FireFox with no difference in the outcome. 
- noticed that CORS errors are appearing that had not appeared previously.

When you click on the Continue button to go to the location page, the log reflects:
1. CORS errors
2. DOM exception
2. location.search.match... is null
3. For the public catalog version, you end up on a page with a GUID URL. For example: https://02f8775c-c248-42d4-be54-2f96443f786a.g0.nr-ext.net/?
4. For  a nerdpack serve, you end up on a NR1 Sandbox page.

Attached is one of the logs I captured for reference and a screen shot of the browser before and after clicking the Continue button. 
[geoops-console-catalog_version.log](https://github.com/newrelic/nr1-workload-geoops/files/6165678/geoops-console-catalog_version.log)

<img width="1192" alt="Maps_Configuration_Page" src="https://user-images.githubusercontent.com/52459310/111661208-34524700-87e5-11eb-95ef-3529357c00f6.png">
<img width="1199" alt="Error_Page_That_Appears_After_Pressing_Continue" src="https://user-images.githubusercontent.com/52459310/111661215-374d3780-87e5-11eb-8b16-f67d88df72c4.png">

**Comment by pmoore123456789** [comment]
Thanks @zstix , much appreciated :)

**Comment by LizBaker** [comment]
we have a hypothesis about a react versioning issue since the platform is semi upgraded to react 17. specifically the react-jsonschema-form library has a form component that this app relies on. we've found a workaround for it that should be fine for now and we could consider swapping out this component entirely at a later time

**Comment by jpvajda** [comment]
@LizBaker YES! amazing work. Thank you so much. 🥳
